site_name: Official Documentation - SSB Sagar Tamang
theme:
  name: material
  favicon: https://raw.githubusercontent.com/SAGAR-TAMANG/ssb-docs/master/img/pi2.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: deep purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/SAGAR-TAMANG/ssb-docs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/sagar-tmg/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/tamang_sagar0000/

markdown_extensions:
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.tilde


copyright: |
  &copy; 2023 <a href="https://sagartamang.com/" target="_blank" rel="noopener">Sagar Tamang</a>