site_name: Docs SSB Sagar Tamang
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: indigo
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: indigo
      accent: deep purple
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: abc
    - icon: fontawesome/brands/linkedin
      link: abc
    - icon: fontawesome/brands/instagram
      link: abc